CREATE database NIXCourseWork;
CREATE USER 'vbondarets' IDENTIFIED BY 'securepass';
GRANT ALL PRIVILEGES ON NIXCourseWork.* TO 'vbondarets';

use NIXCourseWork;

CREATE TABLE IF NOT EXISTS user(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    login VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(36) NOT NULL UNIQUE,
    password VARCHAR(72) NOT NULL,
    role VARCHAR(16) DEFAULT 'USER'
);
CREATE TABLE IF NOT EXISTS basket(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS basket_product(
    id INT NOT NULL  PRIMARY KEY AUTO_INCREMENT,
    product_id INT NOT NULL, 
    basket_id INT NOT NULL
);
CREATE TABLE IF NOT EXISTS product(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(36) NOT NULL,
    price INT NOT NULL,
    rating INT NULL, 
    img VARCHAR(100) NULl,
    typeId INT NOT NULL
);
CREATE TABLE IF NOT EXISTS type(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    class VARCHAR(36) NOT NULL,
    name VARCHAR(36) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS product_info(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    product_id INT NOT NULL, 
    title VARCHAR(36) NOT NULL,
    description VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS review(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    product_id INT NOT NULL,
    grade  INT NOT NULL,
    review VARCHAR(500) NOT NULL,
    date VARCHAR(10) NOT NULL
);